name: Chan Strategy Multi-Index Scan

on:
  workflow_dispatch:
    inputs:
      index_type:
        description: '选择要扫描的指数'
        required: true
        default: 'HSI'
        type: choice
        options:
          - HSI
          - SP500
          - HS300
          - ZZ500
  schedule:
    - cron: '0 10 * * 1-5' # 每天定时运行默认项

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install pandas numpy yfinance plotly akshare lxml

    - name: Run Strategy
      # 传入选择的指数参数
      run: python main.py ${{ github.event.inputs.index_type || 'HSI' }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
